version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Replace with a strong password
      MYSQL_DATABASE: student_db         # Replace with your database name
    volumes:
      - mysql_data:/var/lib/mysql         # Persistent data volume
    ports:
      - "3306:3306"                       # Expose MySQL port
    networks:
      - my_network

  backend:
    build: .
    depends_on:
      - mysql                             # Ensure MySQL container is ready before starting backend
    environment:
      DB_HOST: mysql                      # Use MySQL service name as DB host
      DB_USER: root
      DB_PASSWORD: root_password          # Same as MySQL root password
      DB_NAME: student_db
    ports:
      - "3000:3000"                       # Expose backend port
    networks:
      - my_network

networks:
  my_network:                              # Custom network for communication between containers
    driver: bridge

volumes:
  mysql_data:                               # Persistent storage for MySQL
